### ISSUE TITLE
Problem in using kiwi tool!

### ISSUE THREAD

**Issue by NimaDolatabadi** [emolch/kiwi#10]
when I try to use a basic codes of this program, like this:
`gfdb_extract GFDB/db <<EOF
400000 20000 1 gf1.d400km.z20km.mseed
EOF`
It gave me an error:
nima@Nima:~/Kiwi Training/GFDB$ 
gfdb_extract GFDB/db <<EOF
> 400000 20000 1 gf1.d400km.z20km.mseed
> EOF
gfdb_extract: gfdb: failed to open file: GFDB/db.index
STOP 1
nima@Nima:~/Kiwi Training/GFDB$

what is the problem?

**Comment by emolch** [comment]
Looks like you were running the program from inside the GFDB directory. If you start it there, use
```
gfdb_extract db ...
```

**Comment by NimaDolatabadi** [comment]
@emolch there is another problem here.
when I try to use `snuffler DATA/SYNTH1/DISPL.* --stations="META/stations.dat" --event="META/events.txt"` it goes like this:

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 1, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 2, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 3, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 4, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 5, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 6, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 7, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 8, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 9, file: META/stations.dat`

`snuffler:pyrocko.model        - WARNING  - skipping invalid station/channel definition (line: 10, file: META/stations.dat`
![screenshot from 2017-10-27 16 05 06](https://user-images.githubusercontent.com/32169409/32104320-c3fc8076-bb30-11e7-95e2-550d10a7a71f.png)

what is the problem here? and a windows open with no change..
regards.

**Comment by emolch** [comment]
Maybe the contents of the file `META/stations.dat` is in a different format. The format required by Snuffler is described here: http://pyrocko.org/v0.3/formats/index.html#basic-station-files

**Comment by NimaDolatabadi** [comment]
@emolch @alirezaniki 
Thank you. your answer was a big help.
Best regards

**Comment by NimaDolatabadi** [comment]
@emolch @alirezaniki 
Your answer was a big help.
Thank you
Best Regards
