### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference 

### ISSUE THREAD

**Issue by alirezaniki** [emolch/kiwi#11]
Hi 
I faced the following error during inversion step 2 after bootstrap analysis!
is it just a MEMORY error?
Any idea?
###################################
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x7FE7ADFD16F7
#1  0x7FE7ADFD1D3E
#2  0x7FE7AD4D626F
#3  0x4463C1 in __seismogram_MOD_make_seismogram
#4  0x42895A in __minimizer_engine_MOD_update_syn_probes at minimizer_engine.f90:?
#5  0x42A5B7 in __minimizer_engine_MOD_output_seismograms
#6  0x4056E0 in __minimizer_wrappers_MOD_do_output_seismograms
#7  0x40BE6D in MAIN__ at minimizer.f90:?
^R
sh: line 1: 29778 Segmentation fault      (core dumped) minimizer < ../RESULTS/kshah-a/minimizer.inp2-best > ../RESULTS/kshah-a/minimizer.out2-best
Point source inversion (time domain) - plotting
Plotting results inversion step 2...
########################################
No waveform (neither synthetic nor observation) outputs in step2.ptsolution.ps cause of this error...
Regards

**Comment by emolch** [comment]
Difficult to say. You could recompile kiwi with debug flags enabled and no optimization and find out where in the fortran code it crashes. You could also monitor the memory consumption while it is running with top.

**Comment by alirezaniki** [comment]
This problem just happens sometime so not a permanent issue! 
The TOP command shows nothing wrong with CPU or RAM.
really strange!
Is it only me facing this problem?

**Comment by emolch** [comment]
I just asked Simone, he has not seen this problem before. Is the problem reproducible, in the sense, that same input data deterministically produces the error?

**Comment by alirezaniki** [comment]
No its not, as I said, this problem is not a permanent issue!
I am working on the recent Iran Mw 7.3 earthquake and faced this problem occasionally using a set of data.
I think nothing is wrong with the package and its just my laptop system !
