### ISSUE TITLE
Make 

### ISSUE THREAD

**Issue by JavadKazemian** [emolch/kiwi#13]
After Make encountered the following errors:

gfortran -c  -I/home/javad/src/hdf5-gfortran/include  -I/usr/include -Idummy_omp_lib -O3   gfdb_io_hdf.f90
gfdb_io_hdf.f90:660:70:

         call h5dread_f(dataset, H5T_STD_REF_OBJ, refs2, dims1, error )
                                                                      1
Error: There is no specific subroutine for the generic ‘h5dread_f’ at (1)
gfdb_io_hdf.f90:633:29:

         call h5eset_auto_f(0,egal)
                             1
Error: Type mismatch in argument ‘hdferr’ at (1); passed INTEGER(8) to INTEGER(4)
gfdb_io_hdf.f90:634:43:

         call h5gopen_f( file, name, group, error )
                                           1
....

Thanks in advance for the help

**Comment by NimaDolatabadi** [comment]
@JavadKazemian 

I believe you have not compiled the HDF5 in correct way!
you should download hdf5-1.8.20 or higher from its site. using only `   sudo apt-get install gfortran libhdf5-serial-dev libfftw3-dev` will not install HDF5 and FFTW3 completely.
please download the package, compile and install it according to its README.txt or INSTALL.md.

Best Regards

**Comment by JavadKazemian** [comment]
@NimaDolatabadi 
Thanks,
Worked perfectly!
Cheers
