### ISSUE TITLE
Segmentation fault - invalid memory reference

### ISSUE THREAD

**Issue by NimaDolatabadi** [emolch/kiwi#18]
I have installed the old KIWI software due to extreme amount of errors in installing the new version.
but now I'm experiencing more errors when I run: `./rapidinv rapidinv.inp.synth1` and the errors are listed below:
nima@Dolatabadi:WORK$ ./rapidinv rapidinv.inp.synth1
Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from ../DATA/SYNTH1
radius 0 set to  1000.0
Calling minimizer ../RESULTS/SYNTH1/minimizer.inp.dist
1 ../RESULTS/SYNTH1/minimizer.inp.dist ../RESULTS/SYNTH1/minimizer.out.dist
2 minimizer < ../RESULTS/SYNTH1/minimizer.inp.dist > ../RESULTS/SYNTH1/minimizer.out.dist
Taper applied
Double couple source inversion (freq domain) - step 1
Inversion step 1
Step 1: Rapid mode activated
Calling minimizer ../RESULTS/SYNTH1/minimizer.inp1-run1
1 ../RESULTS/SYNTH1/minimizer.inp1-run1 ../RESULTS/SYNTH1/minimizer.out1-run1
2 minimizer < ../RESULTS/SYNTH1/minimizer.inp1-run1 > ../RESULTS/SYNTH1/minimizer.out1-run1

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f30b3955f3a
#1  0x7f30b395512d
#2  0x7f30b329c4af
#3  0x7f30b40a12b8
#4  0x436c1b
#5  0x42dc26
#6  0x43254e
#7  0x4309a8
#8  0x4329f3
#9  0x446490
#10  0x42898a
#11  0x428aff
#12  0x42ab8e
#13  0x405a30
#14  0x40be29
#15  0x403cac
#16  0x7f30b328782f
#17  0x403cdc
#18  0xffffffffffffffff
Segmentation fault (core dumped)
Analysing results inversion step 1...
10 0
ERROR 1: n start sol <> n point sol (minimizer.out)
this file `minimizer.out` says that everything is `ok`

Regards

**Comment by moscardo** [comment]
Not sure what the problem is. Try running:
minimizer < ../RESULTS/SYNTH1/minimizer.inp1-run1
and check what the output tells.
Simone Cesca

**Comment by NimaDolatabadi** [comment]
I have tried `minimizer < ../RESULTS/SYNTH1/minimizer.inp1-run1` and it gave me the results below,
set_database: ok
set_effective_dt: ok
set_receivers: ok
set_source_location: ok
set_ref_seismograms: ok
set_local_interpolation: ok
set_misfit_method: ok
set_misfit_filter: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_misfit_taper: ok
set_source_params: ok
set_source_params_mask: ok
set_source_subparams_limits: ok

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f96edda2f3a
#1  0x7f96edda212d
#2  0x7f96ed6e94af
#3  0x7f96ee4ee2b8
#4  0x436c1b
#5  0x42dc26
#6  0x43254e
#7  0x4309a8
#8  0x4329f3
#9  0x446490
#10  0x42898a
#11  0x428aff
#12  0x42ab8e
#13  0x405a30
#14  0x40be29
#15  0x403cac
#16  0x7f96ed6d482f
#17  0x403cdc
#18  0xffffffffffffffff
Segmentation fault (core dumped)

I have work with this software so much but now I'm having new errors!!
I'll be glad if you could help me debug this one.
Regards.

**Comment by alirezaniki** [comment]
Dear Nima,
What if you set the Rapid mode "False" in your config file?

**Comment by NimaDolatabadi** [comment]
Dear Alireza,
The problem still exist and it's the same. I have tried so many config file with different inputs and it still is giving me the same error.
I might need to reinstall UBUNTU so that these errors could be related to libraries misbehave.

I'm willing to install the newer version of KIWI but it give errors more then before and need time in order to debug the program.

Regards

**Comment by alirezaniki** [comment]
Give a try the attached rapidinv.py file before re-installing Ubuntu...
[rapidinv.tar.gz](https://github.com/emolch/kiwi/files/3785780/rapidinv.tar.gz)

**Comment by NimaDolatabadi** [comment]
that didn't do the trick as well. 
I will try to install the newer version but errors are extremely high in this one so I'm going to report them here so that this software could be debugged with lower difficulties.
