### ISSUE TITLE
Installation and Compiling

### ISSUE THREAD

**Issue by NimaDolatabadi** [emolch/kiwi#7]
when I use "make" command I get this report:
gfortran -c     -Idummy_omp_lib -O3   comparator.f90
comparator.f90:31: Error: Can't open included file 'fftw3.f'
make: *** [comparator.o] Error 1

At the end I have some errors. How can I fix them?

**Comment by emolch** [comment]
Looks like either fftw is not installed or it cannot find the fftw header file.

Try setting this in `Makefile.local`:
```
INCFFTW = -I/usr/include
```

and replace the path with where `fftw3.f` on you your system, e.g.

```
sudo updatedb
locate fftw3.f
```
