### ISSUE TITLE
Problem using `make`!

### ISSUE THREAD

**Issue by NimaDolatabadi** [emolch/kiwi#8]

**Comment by emolch** [comment]
Hi!
I have seen this problem before: apparently there is an #include
statement missing (or some flag chooses the wrong setup).

In /usr/local/include/libmseed.h:

```
#include <sys/types.h>
#include <unistd.h>
```

Please check that these are both present near the top of this file and
that they are not excluded by any #ifdef.

Best wishes
Sebastian

**Comment by NimaDolatabadi** [comment]
please excuse me for asking too much question. I'm new to this program it always gives me error.
after a lot working with it, simply using `make` gives me these problem listed below:

`gcc -c -std=c99 -Wall  mseed_simple.c
In file included from mseed_simple.c:4:0:
/usr/local/include/libmseed.h:704:3: error: unknown type name ‘off_t’
   off_t packhdroffset;
   ^
/usr/local/include/libmseed.h:705:3: error: unknown type name ‘off_t’
   off_t filepos;
   ^
/usr/local/include/libmseed.h:706:3: error: unknown type name ‘off_t’
   off_t filesize;
   ^
/usr/local/include/libmseed.h:710:79: error: unknown type name ‘off_t’
 extern int      ms_readmsr (MSRecord **ppmsr, const char *msfile, int reclen, off_t *fpos, int *last,
                                                                               ^
/usr/local/include/libmseed.h:713:10: error: unknown type name ‘off_t’
          off_t *fpos, int *last, flag skipnotdata, flag dataflag, flag verbose);
          ^
/usr/local/include/libmseed.h:715:6: error: unknown type name ‘off_t’
      off_t *fpos, int *last, flag skipnotdata, flag dataflag, Selections *selections, flag verbose);
      ^
In file included from mseed_simple.c:4:0:
/usr/local/include/libmseed.h:833:1: error: unknown type name ‘off_t’
 extern off_t lmp_ftello (FILE *stream);
 ^
/usr/local/include/libmseed.h:834:38: error: unknown type name ‘off_t’
 extern int lmp_fseeko (FILE *stream, off_t offset, int whence);
                                      ^
mseed_simple.c: In function ‘writemseed’:
mseed_simple.c:61:38: warning: passing argument 7 of ‘mst_pack’ from incompatible pointer type [enabled by default]
                                      1, &psamples, 1, 0, NULL);
                                      ^
In file included from mseed_simple.c:4:0:
/usr/local/include/libmseed.h:674:22: note: expected ‘int64_t *’ but argument is of type ‘int *’
 extern int           mst_pack (MSTrace *mst, void (*record_handler) (char *, int, void *),
                      ^
mseed_simple.c:16:27: warning: variable ‘precords’ set but not used [-Wunused-but-set-variable]
     int         psamples, precords;
                           ^
make: *** [mseed_simple.o] Error 1`

**Comment by emolch** [comment]
Did you add the two lines:

```
#include <sys/types.h>
#include <unistd.h>
```

to the top of `libmseed.h`?

**Comment by NimaDolatabadi** [comment]
@emolch 
I just solved the problem on my own. but I think I should put the solution here so maybe someone would need it.
after compiling and installing HDF5, FFTW3, libmseed and SAC I just tried to install KIWI using `make` but it runs with error that [mseed_simple.o] Error 1 
beware that `makefile.local` must change to your need.
 commands below will solve the problem:
note that my `kiwi` directory is inside home so change the directory as your system goes.
`cd ~/kiwi/mseed`
`gcc -c mseed_simple.c`
this will make [mseed_simple.o]. now you need [libmseed.h] and [libmseed.a] so simple copy these files from libmseed directory that you compiled in `~/kiwi/mseed`. now use `cd ..` and try using `make`
This will actually solve the problem.
Best Regards
